version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2017
configuration: Release
clone_depth: 50

pull_requests:
  do_not_increment_build_number: true

#skip_branch_with_pr: true
skip_commits:
  files:
    - docs/*
    - media/*
    - LICENSE
    - mkdocs.yml
    - README.md
    - .travis.yml
    - .gitignore

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  clone_folder: C:\projects\easycaching\

  install:
  - ps: cd c:\projects\easycaching\tools\RedisConfigs\3.0.503\
  - ps: .\redis-server.exe --service-install --service-name "redis-6379" "..\Basic\master-6379.conf"
  - ps: .\redis-server.exe --service-install --service-name "redis-6380" "..\Basic\master-6380.conf"
  - ps: .\redis-server.exe --service-install --service-name "redis-6388" "..\Basic\master-6388.conf"
  - ps: net start redis-6379
  - ps: net start redis-6380
  - ps: net start redis-6388
  - ps: new-service –Name memcached1 –DisplayName memcached1 –BinaryPathName “c:\projects\easycaching\tools\memcached\memcached.exe -d runservice -m 64 -c 2048 -p 11211” –StartupType Automatic
  - ps: new-service –Name memcached2 –DisplayName memcached2 –BinaryPathName “c:\projects\easycaching\tools\memcached\memcached.exe -d runservice -m 64 -c 2048 -p 11212” –StartupType Automatic  
  - ps: net start memcached1
  - ps: net start memcached2
  - ps: cd c:\projects\easycaching
                
  before_build:
  - ps: dotnet restore

  build_script:
  - ps: dotnet build -c Release

  test_script:
  - ps: dotnet test -c Release --no-build .\test\EasyCaching.UnitTests\EasyCaching.UnitTests.csproj

-
  matrix:
    only:
      - image: Ubuntu1804

  clone_folder: /home/appveyor/projects/easycaching

  services:
  - redis

  install:
  #- sh: sudo apt-get install libevent libevent-deve
  - sh: redis-server /home/appveyor/projects/easycaching/tools/RedisConfigs/Basic/master-6388.conf
  - sh: redis-server /home/appveyor/projects/easycaching/tools/RedisConfigs/Basic/master-6380.conf
  - sh: sudo apt-get install memcached
  - sh: sudo memcached -p 11211 -u root -m 64m -d
  - sh: sudo memcached -p 11212 -u root -m 64m -d
    
  before_build:
  - sh: dotnet restore
  
  build_script:
  - sh: dotnet build -c Release
  
  test_script:
   - sh: dotnet test -c Release --no-build ./test/EasyCaching.UnitTests/EasyCaching.UnitTests.csproj
  
   