site_name: EasyCaching
theme: readthedocs
repo_url: https://github.com/dotnetcore/EasyCaching

pages:
- Introduction: index.md
- Features : Features.md
- Caching Provider:
    - In-Memory : In-Memory.md
    - Redis : Redis.md
    - Memcached : Memcached.md
    - SQLite : SQLite.md
    - Hybird : Hybrid.md
    - ProviderFactory : ProviderFactory.md
- Caching Interceptor:
    - AspectCore : AspectCore.md
    - Castle : Castle.md
- Caching Serializer:
    - BinaryFormatter : BinaryFormatter.md
    - MessagePack : MessagePack.md
    - Json : Json.md
    - Protobuf : ProtoBuf.md
    
